services:
  api:
    build: ./backend
    ports:
      - "8000:8000"

  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - api

  web:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway
